### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by Roobyx** [mohux/react-brackets#14]
Hey mate, great work!

I just cloned the repo to check it out and ran the example as suggested in the main README.
It doesn't run out of the box with there being  2 issues:
1. Wrong definition of the RenderSeedProps or wrong restructuring of it in the losing-brackets.tsx (breaks double elim)
Its defined as "roundIndex", but used as "roundIdx"
2. I am not sure how you are trying to get the index of the current "isLineConnector" again in the losing-brackets.tsx (breaks double elim), but it is always undefined there for it cant get the seed length. It generally works if you add a value, like 1.

**Comment by mohux** [comment]
Hi buddy, thank you so much for your kind words

I think the examples are outdated to last update, my bad and my mistake, totally sorry

will fix it in the next 2 days with an update coming to the repo containing some fixes.

next update will contain little more features requested by people,

thanks for letting me know!

**Comment by humarkx** [comment]
@mohux Any updates on the new examples? Would love it, thanks.

**Comment by LeandroFontellas** [comment]
@humarkx hey bro, i've done some changes in the project and it seems the examples is back to fully working now, i have tested them so i believe this issue can be closed now.

**Comment by mohux** [comment]
@LeandroFontellas perfect
Thanks for letting me know
