### ISSUE TITLE
renterTitleComponent not working

### ISSUE THREAD

**Issue by mosprogrammer** [mohux/react-brackets#2]

**Comment by mohammadou1** [comment]
It should be working properly
Can you provide a reproduction of the error?

**Comment by mosprogrammer** [comment]
In document you type renterTitleComponent but in code use roundTitleComponent

**Comment by mohammadou1** [comment]
Oh its a typo in the document
Am sorry, thanks for notifying me

**Comment by Zohaib-Javed** [comment]
Why didn't you updated the document yet? As, it has been several months since this issue has been pointed out.

**Comment by mohux** [comment]
Its updated, a pull request was made but forgot to merge.
