### ISSUE TITLE
Can we use this library with the react native

### ISSUE THREAD

**Issue by arunabhverma** [mohux/react-brackets#3]
I want to achieve something related to this libraries design and animation and flow. So can I use this library with the react native.
If not then there any alternate library for this type of design.
I am attaching this video, that is exact i want to achieve.

https://user-images.githubusercontent.com/59590144/111297632-d6522200-8673-11eb-8263-6042a49d15f1.MP4

**Comment by mohammadou1** [comment]
Sadly no, only as a web view though
I think there are alternatives on RN, if not, we can see hoe we can build a support for RN

**Comment by arunabhverma** [comment]
thank you sir

**Comment by arunabhverma** [comment]
Do you know any alternative this library in rn

**Comment by mohux** [comment]
Not really, am so sorry

**Comment by kr396** [comment]
> I want to achieve something related to this libraries design and animation and flow. So can I use this library with the react native. If not then there any alternate library for this type of design. I am attaching this video, that is exact i want to achieve.
> 
>  RPReplay_Final1615891908.MP4

Have you found any solution?

**Comment by arunabhverma** [comment]
Not really! I wrote the logic to render this type of UI (can be found in this lib as well) and added layout animations for the animated effect for react native.

**Comment by kr396** [comment]
> Not really! I wrote the logic to render this type of UI (can be found in this lib as well) and added layout animations for the animated effect for react native.

Thanks for the update @arunabhverma. Could ypu share that component via email?
