### ISSUE TITLE
Value to Generate the winner or Loser

### ISSUE THREAD

**Issue by mzcoder-hub** [mohux/react-brackets#7]
hi i interest in this repository because now i looking for easy way to generate bracket for esport web apps project, theres a seed in this react-brackets library, but may i know is there a custom seed can added in the seed ?, maybe add the winner or the loser status ?

**Comment by mohux** [comment]
Hi, thanks a lot for your interest
Yes you can customize the seed like you wish to

renderSeedComponent will accept a component and will pass any props you pass through the rounds array to every seed
