### ISSUE TITLE
[Feature] Be able to style the lines that connect brackets.

### ISSUE THREAD

**Issue by TwoForTen** [mohux/react-brackets#9]
Hi guys, this is a great package and I would love to use it on a project of mine, however, my project requires the lines to be editable. For more context, I need to be able to color the lines when a user hovers over a team to clearly see how they got to where they are now.
Hope you guys get around to open up more customisation in that regard.

**Comment by TwoForTen** [comment]
How would I go about selecting those lines? I can see they are actually ::after pseudo elements, so is there any way to grab them via JS or CSS?
Also, thanks for the quick response!

**Comment by mohammadou1** [comment]
You can for sure, but using customSeed and adding a class to Seed Component, 
I will make sure next update has better docs and easier customization
